version: 2
jobs:
  build:
    docker:
      - image: cimg/node:18.0.0
    resource_class: small
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - run:
          name: Download Dependencies
          command: npm install
      - run:
          name: Verify (Standard)
          command: npm run test
      - save_cache:
          paths:
            - ~/node_modules
          key: dependencies-{{ checksum "package-lock.json" }}